### ISSUE TITLE
[Feature] Rename rooms

### ISSUE THREAD

**Issue by Atn-D** [MangoCubes/remotrix#9]
Is it planned to be able to rename rooms to make it easier to find out which contact is linked to it?

Ideally, it should synchronize with the contact book to retrieve the name, or even the profile photo.

---

Thank you for this very promising start to the project!

**Comment by MangoCubes** [comment]
Currently, the app stores all "Matrix Account"-"Room ID"-"SMS Sender" triplets in its own database, meaning you can freely change the room name. I will check on accessing contacts to fetch sender username, and using that as default room name and topic. Yeah, I think it is doable, and I will work on that next.

**Comment by MangoCubes** [comment]
Feature has been included in the newest release 0.3.

![image](https://github.com/MangoCubes/remotrix/assets/10383115/5943992c-0f82-4772-bcb7-012d1332e288)
![image](https://github.com/MangoCubes/remotrix/assets/10383115/885e203b-1d38-4f0d-85d5-5f2e36e07e40)
